add_newline = false
continuation_prompt = "∙  ┆ "
format = "$hostname$nix_shell$os$directory$battery$container$git_branch $git_state$python$nodejs$bun$deno$lua$rust$java$c$cpp$cmake$golang$cmd_duration$jobs$status$line_break[❯](bold green)${custom.space}"

[battery]
disabled = false
format = " [](fg:bright-black)[$path](bg:bright-black fg:white)[](fg:bright-black)"

[bun]
format = "[$symbol ](blue)"
symbol = ""

[c]
format = "[$symbol ](blue)"
symbol = ""

[cmake]
format = "[$symbol ](blue)"
symbol = ""

[cmd_duration]
format = "[$duration ](fg:yellow)"
min_time = 1000

[container]
format = "[$symbol ](yellow dimmed)"
symbol = " 󰏖"

[cpp]
format = "[$symbol ](blue)"
symbol = ""

[custom.space]
format = " "
when = "! test $env"

[dart]
format = "[$symbol ](blue)"
symbol = ""

[deno]
format = "[$symbol ](blue)"
symbol = ""

[directory]
format = " [](fg:bright-black)[$path](bg:bright-black fg:white)[](fg:bright-black) [$read_only]($read_only_style)"
read_only = " "
read_only_style = "fg:yellow"
truncate_to_repo = true
truncation_length = 4
truncation_symbol = ""

[elixir]
format = "[$symbol ](purple)"
symbol = ""

[git_branch]
format = "[ $symbol $branch](fg:purple)(:$remote_branch)"
style = ""
symbol = ""

[git_state]
format = "[](fg:yellow)[$state( $progress_current/$progress_total)](bg:yellow fg:black)[](fg:yellow) "

[golang]
format = "[$symbol ](blue)"
symbol = ""

[hostname]
format = "[](fg:base04)[$ssh_symbol $hostname](bg:base04 fg:white)[](fg:base04) "
ssh_only = true
ssh_symbol = ""

[java]
format = "[$symbol ](red)"
symbol = ""

[line_break]
disabled = false

[lua]
format = "[$symbol ](blue)"
symbol = "󰢱"

[nix_shell]
disabled = false
format = "[](fg:white)[ ](bg:white fg:black)[](fg:white) "

[nodejs]
format = "[$symbol ](bright-blue)"
symbol = "󰛦"

[os]
disabled = false
format = "$symbol"

[os.symbols]
Alpine = "[ ](fg:bright-blue)"
Arch = "[ ](fg:bright-blue)"
Debian = "[ ](fg:red)"
EndeavourOS = "[ ](fg:purple)"
Fedora = "[ ](fg:blue)"
Macos = "[ ](fg:white)"
NixOS = "[ ](fg:green)"
SUSE = "[ ](fg:green)"
Ubuntu = "[ ](fg:bright-purple)"
openSUSE = "[ ](fg:green)"

[python]
format = "[$symbol ](yellow)"
symbol = ""

[rust]
format = "[$symbol ](red)"
symbol = ""

[status]
disabled = false
format = "[$symbol](fg:red)"
map_symbol = true
not_executable_symbol = " Can't Execute"
not_found_symbol = "󰍉 Not Found"
sigint_symbol = "󰂭 "
signal_symbol = "󱑽 "
success_symbol = ""
symbol = "✗"
