[colors.primary]
background = "#1a120e"
foreground = "#f0dfd8"

[colors.cursor]
text = "#1a120e"
cursor = "#ffb692"

[colors.normal]
black = "#1a120e"
red = "#ffb4ab"
green = "#ffb692"
yellow = "#e6beac"
blue = "#d0c890"
magenta = "#703717"
cyan = "#5c4033"
white = "#f0dfd8"

[colors.bright]
black = "#423732"
red = "#ffb4ab"
green = "#ffb692"
yellow = "#e6beac"
blue = "#d0c890"
magenta = "#703717"
cyan = "#5c4033"
white = "#f0dfd8"

